Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.synced_folder "share/", "/share"
  #config.vm.network "forwarded_port", guest: 80, host: 8181
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "docker"
  end
  config.vm.provision "shell", path: "provisioner.sh"
end